#!/usr/bin/env perl

use strict;
use warnings;
use IronMunger;
use File::Path qw(rmtree);
use File::Copy::Recursive qw(dircopy);

rmtree('output');
dircopy('share','output');

my $munger = IronMunger->load_from_plagger('csv');

print $munger->debug_dump;

$munger->save_monger_stats('output');
